name: "Ty's Site"
favicon: null
layout_spectrum: 1
typography_spectrum: 0.10150258522480726
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#000000'
    - '#d2c7bb'
    - '#5f8f25'
    - '#263107'
  brandStrength: 0.5
  lightness: 0.5625
  saturation: 0.125
  rhythmicContrast: 0.75
purpose: []
