name: "Ty's Site"
favicon: null
layout_spectrum: 0.026616933522745967
typography_spectrum: 0.10150258522480726
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors: []
  brandStrength: 0.9769367347471416
  lightness: 0.487538201501593
  saturation: 0.956576817901805
  rhythmicContrast: 0.016809985740110278
purpose: []
